# Generated by Django 4.2.4 on 2023-08-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_watchlist_comment_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_price', to='auctions.auction'),
        ),
    ]
