# Generated by Django 4.2.4 on 2023-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_title_watchlist_item_alter_auction_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
