# Generated by Django 4.2.4 on 2023-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bet_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
