# Generated by Django 4.2.4 on 2023-09-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
