# Generated by Django 4.2.5 on 2023-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_like', models.CharField(max_length=120)),
                ('username_like', models.CharField(max_length=120)),
            ],
        ),
    ]
