# Generated by Django 4.2.5 on 2023-10-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='like',
        ),
    ]
